### ISSUE TITLE
filterdata not working

### ISSUE THREAD

**Issue by yogeshgabani** [Harish-b-03/filter#1]
in this example when i click button to filter data no filtered data to display on any click event..
so please update code to filter data so i view selected data on selected category.

**Comment by Harish-b-03** [comment]
Hi @yogeshgabani :wave: ,

I’ve fixed the issue. I think the API response was updated, which caused the problem. Thanks for reporting it!

You can check the changes I made [here](https://github.com/Harish-b-03/filter/commit/2b601bc1e0580194285c36d3299fe2afd5704ff9).

Happy coding!

Thank you.
